// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMH2vg9s2P4UGoZIwTg44YYlyupHOUciE',
    appId: '1:489549694454:web:2ae28b38b2aad0f631f3d7',
    messagingSenderId: '489549694454',
    projectId: 'flutter-blog-10a12',
    authDomain: 'flutter-blog-10a12.firebaseapp.com',
    storageBucket: 'flutter-blog-10a12.appspot.com',
    measurementId: 'G-RWE0C716P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkVEMRuOPJWNeSmLEDs7n9n9VW6BdHJPU',
    appId: '1:489549694454:android:a6f5ec00416efc6f31f3d7',
    messagingSenderId: '489549694454',
    projectId: 'flutter-blog-10a12',
    storageBucket: 'flutter-blog-10a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByHEyeWrrrl4Yd0FPJ0ouVvfEvy7v8A78',
    appId: '1:489549694454:ios:2678bb4a944540ba31f3d7',
    messagingSenderId: '489549694454',
    projectId: 'flutter-blog-10a12',
    storageBucket: 'flutter-blog-10a12.appspot.com',
    iosBundleId: 'com.example.flutterBlog',
  );
}
